from readchar import key


KEY_MAPPINGS = {
    key.BACKSPACE: "BackSpace",
    key.UP: "Up",
    key.DOWN: "Down",
    key.LEFT: "Left",
    key.RIGHT: "Right",
    key.SPACE: "space",
    key.ENTER: "Enter",
    key.ESC: "Escape",
    key.TAB: "Tab",
    "\x1b\x1b": "Escape",
    "*": "asterisk",
    ",": "comma",
    ".": "period",
    ":": "colon",
    ";": "semicolon",
    "-": "minus",
    "+": "plus",
    "_": "underscore",
    "'": "apostrophe",
    '"': "quotedbl",
    "[": "bracketleft",
    "]": "bracketright",
    "{": "braceleft",
    "}": "braceright",
    key.CTRL_A: "ctrl+a",
    key.CTRL_B: "ctrl+b",
    key.CTRL_C: "ctrl+c",
    key.CTRL_D: "ctrl+d",
    key.CTRL_E: "ctrl+e",
    key.CTRL_F: "ctrl+f",
    key.CTRL_G: "ctrl+g",
    key.CTRL_H: "ctrl+h",
    key.CTRL_I: "ctrl+i",
    key.CTRL_K: "ctrl+k",
    key.CTRL_L: "ctrl+l",
    key.CTRL_M: "ctrl+m",
    key.CTRL_N: "ctrl+n",
    key.CTRL_O: "ctrl+o",
    key.CTRL_P: "ctrl+p",
    key.CTRL_Q: "ctrl+q",
    key.CTRL_R: "ctrl+r",
    key.CTRL_S: "ctrl+s",
    key.CTRL_T: "ctrl+t",
    key.CTRL_U: "ctrl+u",
    key.CTRL_V: "ctrl+v",
    key.CTRL_W: "ctrl+w",
    key.CTRL_X: "ctrl+x",
    key.CTRL_Y: "ctrl+y",
    key.CTRL_Z: "ctrl+z",
    key.ALT_A: "custom",
}

MOUSE_DIRECTIONS = {
    "A": 0,
    "B": 180,
    "C": 90,
    "D": 270,
}
